### ISSUE TITLE
Incompatible with Certain Chat Plugins

### ISSUE THREAD

**Issue by PseudoResonance** [rayanbzd/ZenChatHistory#1]
This plugin appears to be incompatible with chat plugins like [Carbon](https://github.com/Hexaoxide/Carbon/) due to the way they capture messages on the server side instead of the proxy.

I see that the plugin only captures system type messages at the moment, whereas I believe Carbon sends chat type messages.

**Comment by rayanbzd** [comment]
Fixed in 1.0.2-SNAPSHOT
