### ISSUE TITLE
Duplicated chat when switching back to a previous server

### ISSUE THREAD

**Issue by PseudoResonance** [rayanbzd/ZenChatHistory#3]
The client appears to keep track of chat on a per-server basis, so if you switch back to a server later, your chat messages will be duplicated.

For example, in the provided image, I first join the survival server and say "hello". Then I switch to the minigame server and say "I'm on minigame". At this point, the chat looks as expected.
![image](https://github.com/rayanbzd/ZenChatHistory/assets/7216500/4890620d-23c5-4925-b5f5-f00a804fd60e)
However, upon switching back to the survival server, the client has retained its chat history from before, and the plugin appends the same messages below. This makes the chat log confusing and messy.
![image](https://github.com/rayanbzd/ZenChatHistory/assets/7216500/3655e846-0e31-4288-95d0-1de2a5c3e02e)

I can think of 2 possible solutions to this.
1. Send ~50 empty messages to the user on server change to clear their existing chat.
2. Keep track of what server each message was sent on and avoid sending a message on the same server it originated from.

**Comment by PseudoResonance** [comment]
After doing some testing, I was unable to figure out the exact conditions for when a message would be saved to the server's log. I think the most guaranteed option is to simply clear the chat with empty messages.
I pushed my experimental code [here](https://github.com/PseudoResonance/ZenChatHistory/tree/track-message-servers) if you'd like to see. It is just a quick and dirty test though.

**Comment by rayanbzd** [comment]
Fixed in 1.0.2-SNAPSHOT
