### ISSUE TITLE
More bugs

### ISSUE THREAD

**Issue by msmanui** [rayanbzd/ZenChatHistory#5]
![image](https://github.com/rayanbzd/ZenChatHistory/assets/63617395/b0fa5798-48e5-4872-a518-46f811baf1f8)
This is in the action bar, the messge of being in combat (Deluxecombat plugin) and when swithcing of servers its appear like this? 
And sometimes lot of messages are repated

**Comment by rayanbzd** [comment]
Fixed in 1.0.2-SNAPSHOT
